# Generated by Django 4.0.4 on 2022-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_day',
            field=models.DateField(null=True),
        ),
    ]
