# Generated by Django 4.0.4 on 2022-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pass_chaged',
            field=models.BooleanField(default=False),
        ),
    ]
