# Generated by Django 4.0.4 on 2022-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_pass_chaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='desc',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
