# Generated by Django 4.0.4 on 2022-04-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_target_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
